data = {
	vegetarian: false,
	vegan: false,
	glutenFree: true,
	dairyFree: false,
	veryHealthy: false,
	cheap: false,
	veryPopular: false,
	sustainable: false,
	servings: 4,
	sourceUrl: 'http://www.foodista.com/recipe/VJSXFQZ8/new-waldorf-salad',
	spoonacularSourceUrl: 'https://spoonacular.com/new-waldorf-salad-653068',
	aggregateLikes: 1,
	creditText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
	license: 'CC BY 3.0',
	sourceName: 'Foodista',
	extendedIngredients: [{
		aisle: 'Produce',
		name: 'apple',
		amount: 2,
		unit: 'cups',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '2 cups diced apple',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Spices and Seasonings',
		name: 'black pepper',
		amount: 0.25,
		unit: 'teaspoon',
		unitShort: 't',
		unitLong: 'teaspoons',
		originalString: '1/4 teaspoon freshly ground black pepper to taste',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'celery',
		amount: 4,
		unit: 'rib',
		unitShort: 'rib',
		unitLong: 'ribs',
		originalString: '4 celery ribs, chopped',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Condiments',
		name: 'fat-free mayonnaise',
		amount: 0.5,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/2 cup fat-free mayonnaise',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'lemon juice',
		amount: 2,
		unit: 'teaspoons',
		unitShort: 't',
		unitLong: 'teaspoons',
		originalString: '2 teaspoons lemon juice',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Baking',
		name: 'raisins',
		amount: 0.25,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/4 cup raisins',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'red leaf lettuce leaves',
		amount: 1,
		unit: 'leaves',
		unitShort: 'leaves',
		unitLong: 'leave',
		originalString: 'Red-leaf lettuce leaves for serving',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Spices and Seasonings',
		name: 'salt',
		amount: 1,
		unit: 'teaspoon',
		unitShort: 't',
		unitLong: 'teaspoon',
		originalString: '1 teaspoon salt, or to taste',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Nuts',
		name: 'walnuts',
		amount: 0.5,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/2 cup toasted walnuts',
		metaInformation: [],
		longNameAdditions: []
	}],
	id: 653068,
	title: 'New Waldorf Salad',
	readyInMinutes: 45,
	image: 'New-Waldorf-Salad-653068.jpg',
	imageUrls: ['New-Waldorf-Salad-653068.jpg']
}, {
	vegetarian: true,
	vegan: false,
	glutenFree: true,
	dairyFree: false,
	veryHealthy: false,
	cheap: false,
	veryPopular: false,
	sustainable: false,
	servings: 1,
	sourceUrl: 'http://www.foodista.com/recipe/PXSGNFC6/swiss-bircher-muesli',
	spoonacularSourceUrl: 'https://spoonacular.com/swiss-bircher-muesli-662665',
	aggregateLikes: 1,
	creditText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
	license: 'CC BY 3.0',
	sourceName: 'Foodista',
	extendedIngredients: [{
		aisle: 'Produce',
		name: 'apple',
		amount: 1,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '1 Apple',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Milk, Eggs, Other Dairy',
		name: 'milk',
		amount: 0.5,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/2 cup of Milk',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Cereal',
		name: 'muesli',
		amount: 0.5,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/2 cup muesli',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Milk, Eggs, Other Dairy',
		name: 'skim vanilla yoghurt',
		amount: 3,
		unit: 'tablespoons',
		unitShort: 'T',
		unitLong: 'tablespoons',
		originalString: '3 tablespoons of plain or vanilla yoghurt',
		metaInformation: [],
		longNameAdditions: []
	}],
	id: 662665,
	title: 'Swiss Bircher Muesli',
	readyInMinutes: 45,
	image: 'Swiss-Bircher-Muesli-662665.jpg',
	imageUrls: ['Swiss-Bircher-Muesli-662665.jpg']
}, {
	vegetarian: true,
	vegan: false,
	glutenFree: false,
	dairyFree: false,
	veryHealthy: false,
	cheap: false,
	veryPopular: false,
	sustainable: false,
	servings: 1,
	sourceUrl: 'http://www.foodista.com/recipe/3BCP244Z/easy-delish-apple-crumble',
	spoonacularSourceUrl: 'https://spoonacular.com/easy-delish-apple-crumble-641803',
	aggregateLikes: 1,
	creditText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
	license: 'CC BY 3.0',
	sourceName: 'Foodista',
	extendedIngredients: [{
		aisle: 'Produce',
		name: 'apples',
		amount: 3,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '3 apples – sliced',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Baking',
		name: 'brown sugar',
		amount: 0.5,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/2 cup of brown sugar',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Milk, Eggs, Other Dairy',
		name: 'butter',
		amount: 0.75,
		unit: 'stick',
		unitShort: 'stick',
		unitLong: 'sticks',
		originalString: '3/4 stick of butter',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Baking',
		name: 'flour',
		amount: 1,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cup',
		originalString: '1 cup of flour',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Spices and Seasonings',
		name: 'ground cloves',
		amount: 1,
		unit: 'Dash',
		unitShort: 'Dash',
		unitLong: 'Dash',
		originalString: 'Dash of ground cloves',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'lemon zest',
		amount: 1,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '1 Zest of lemon',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Baking',
		name: 'sugar',
		amount: 0.5,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/2 cup of sugar',
		metaInformation: [],
		longNameAdditions: []
	}],
	id: 641803,
	title: 'Easy & Delish! ~ Apple Crumble',
	readyInMinutes: 45,
	image: 'Easy---Delish--Apple-Crumble-641803.jpg',
	imageUrls: ['Easy---Delish--Apple-Crumble-641803.jpg']
}, {
	vegetarian: true,
	vegan: false,
	glutenFree: false,
	dairyFree: true,
	veryHealthy: false,
	cheap: false,
	veryPopular: false,
	sustainable: false,
	servings: 2,
	sourceUrl: 'http://www.foodista.com/recipe/T5DDYH8M/homemade-muesli',
	spoonacularSourceUrl: 'https://spoonacular.com/homemade-muesli-breakfast-cereal-647043',
	aggregateLikes: 1,
	creditText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
	license: 'CC BY 3.0',
	sourceName: 'Foodista',
	extendedIngredients: [{
		aisle: 'Produce',
		name: 'apple',
		amount: 1,
		unit: 'handful',
		unitShort: 'handful',
		unitLong: 'handful',
		originalString: '1 handful Apple Chunks',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Nuts',
		name: 'cashews',
		amount: 1,
		unit: 'handful',
		unitShort: 'handful',
		unitLong: 'handful',
		originalString: '1 handful Cashews, Almonds and/or Walnuts',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Cereal',
		name: 'corn flakes',
		amount: 0.25,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/4 cup Corn Flakes/Bran Flakes',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Dried Fruit',
		name: 'craisins',
		amount: 1,
		unit: 'handful',
		unitShort: 'handful',
		unitLong: 'handful',
		originalString: '1 handful Craisins, Raisins, Apricots, Figs',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Nut butters, Jams, and Honey',
		name: 'honey',
		amount: 1,
		unit: 'tablespoon',
		unitShort: 'T',
		unitLong: 'tablespoon',
		originalString: '1 tablespoon Honey',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Oil, Vinegar, Salad Dressing',
		name: 'olive oil',
		amount: 1,
		unit: 'tablespoon',
		unitShort: 'T',
		unitLong: 'tablespoon',
		originalString: '1 tablespoon Olive oil',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Cereal',
		name: 'rolled oats',
		amount: 0.25,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/4 cup Uncooked quick rolled Oats',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Ethnic Foods',
		name: 'sesame seeds',
		amount: 1,
		unit: 'teaspoon',
		unitShort: 't',
		unitLong: 'teaspoon',
		originalString: '1 teaspoon Sesame seeds',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Baking',
		name: 'wheat bran',
		amount: 1,
		unit: 'tablespoon',
		unitShort: 'T',
		unitLong: 'tablespoon',
		originalString: '1 tablespoon Wheat Bran',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Health Foods',
		name: 'wheat germ',
		amount: 1,
		unit: 'tablespoon',
		unitShort: 'T',
		unitLong: 'tablespoon',
		originalString: '1 tablespoon Wheat Germ',
		metaInformation: [],
		longNameAdditions: []
	}],
	id: 647043,
	title: 'Homemade Muesli Breakfast Cereal',
	readyInMinutes: 90,
	image: 'Homemade-Muesli-647043.jpg',
	imageUrls: ['Homemade-Muesli-647043.jpg']
}, {
	vegetarian: false,
	vegan: false,
	glutenFree: false,
	dairyFree: true,
	veryHealthy: false,
	cheap: false,
	veryPopular: false,
	sustainable: false,
	servings: 10,
	sourceUrl: 'http://www.foodista.com/recipe/GWL8CZQD/quick-apple-ginger-pie',
	spoonacularSourceUrl: 'https://spoonacular.com/quick-apple-ginger-pie-657563',
	aggregateLikes: 1,
	creditText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
	license: 'CC BY 3.0',
	sourceName: 'Foodista',
	extendedIngredients: [{
		aisle: 'Produce',
		name: 'apples',
		amount: 4,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '4 mediums apples, peel, cored, quartered and sliced',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Milk, Eggs, Other Dairy',
		name: 'egg',
		amount: 1,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '1 egg wash, optional (1 egg white and a tsp of water)',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Baking',
		name: 'flour',
		amount: 1,
		unit: 'tablespoon',
		unitShort: 'T',
		unitLong: 'tablespoon',
		originalString: '1 tablespoon flour',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'fresh ginger',
		amount: 1,
		unit: 'inch',
		unitShort: 'inch',
		unitLong: 'inch',
		originalString: '1 inch fresh ginger',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Spices and Seasonings',
		name: 'ground cinnamon',
		amount: 1,
		unit: 'tablespoon',
		unitShort: 'T',
		unitLong: 'tablespoon',
		originalString: '1 tablespoon ground cinnamon',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Spices and Seasonings',
		name: 'ground nutmeg',
		amount: 1,
		unit: 'teaspoon',
		unitShort: 't',
		unitLong: 'teaspoon',
		originalString: '1 teaspoon ground nutmeg (depending on how much you like the spice)',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'lemon',
		amount: 1,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '1 lemon, juiced',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Frozen',
		name: 'pie shells',
		amount: 2,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '2 pie shells (1 if you want an open-faced pie)',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Baking',
		name: 'white sugar',
		amount: 1,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cup',
		originalString: '1 cup sugar (I used half brown and half white)',
		metaInformation: [],
		longNameAdditions: []
	}],
	id: 657563,
	title: 'Quick Apple Ginger Pie',
	readyInMinutes: 45,
	image: 'Quick-Apple-Ginger-Pie-657563.jpg',
	imageUrls: ['Quick-Apple-Ginger-Pie-657563.jpg']
}, {
	vegetarian: true,
	vegan: false,
	glutenFree: true,
	dairyFree: false,
	veryHealthy: false,
	cheap: false,
	veryPopular: false,
	sustainable: false,
	servings: 1,
	sourceUrl: 'http://www.foodista.com/recipe/K232GXCT/chilled-swiss-oatmeal',
	spoonacularSourceUrl: 'https://spoonacular.com/chilled-swiss-oatmeal-638604',
	aggregateLikes: 6,
	creditText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
	license: 'CC BY 3.0',
	sourceName: 'Foodista',
	extendedIngredients: [{
		aisle: 'Produce',
		name: 'apple',
		amount: 1,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '1 small apple, chopped',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'banana',
		amount: 1,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '1 small banana, chopped',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Baking',
		name: 'raisins',
		amount: 2,
		unit: 'tablespoon',
		unitShort: 'T',
		unitLong: 'tablespoons',
		originalString: '2-3 tablespoon raisins',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Milk, Eggs, Other Dairy',
		name: 'milk',
		amount: 0.3333333333333333,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/3 cup milk of your choice',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Savory Snacks',
		name: 'peanuts',
		amount: 1,
		unit: 'tablespoon',
		unitShort: 'T',
		unitLong: 'tablespoon',
		originalString: '1 tablespoon peanuts',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Cereal',
		name: 'oatmeal',
		amount: 0.5,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/2 cup old-fashioned oatmeal (may use steel cut but not the instant kind)',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Milk, Eggs, Other Dairy',
		name: 'vanilla yogurt',
		amount: 6,
		unit: 'oz',
		unitShort: 'oz',
		unitLong: 'ounces',
		originalString: '6 oz low-fat vanilla yogurt (if using plain yogurt, add honey for sweetness)',
		metaInformation: [],
		longNameAdditions: []
	}],
	id: 638604,
	title: 'Chilled Swiss Oatmeal',
	readyInMinutes: 15,
	image: 'Chilled-Swiss-Oatmeal-638604.jpg',
	imageUrls: ['Chilled-Swiss-Oatmeal-638604.jpg']
}, {
	vegetarian: false,
	vegan: false,
	glutenFree: true,
	dairyFree: false,
	veryHealthy: false,
	cheap: false,
	veryPopular: false,
	sustainable: false,
	servings: 4,
	sourceUrl: 'http://www.foodista.com/recipe/Z78YK567/appetizing-apple-and-almond-soup',
	spoonacularSourceUrl: 'https://spoonacular.com/appetizing-apple-and-almond-soup-632449',
	aggregateLikes: 4,
	creditText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
	license: 'CC BY 3.0',
	sourceName: 'Foodista',
	extendedIngredients: [{
		aisle: 'Nuts',
		name: 'almonds',
		amount: 8,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '8 Almonds',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'apples',
		amount: 2,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '2 Apples',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'carrots',
		amount: 0.5,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/2 cup Carrots',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Spices and Seasonings',
		name: 'cinnamon',
		amount: 0.5,
		unit: 'teaspoon',
		unitShort: 't',
		unitLong: 'teaspoons',
		originalString: '1/2 teaspoon cinnamon',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'gooseberry',
		amount: 1,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '1 Gooseberry',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Milk, Eggs, Other Dairy',
		name: 'heavy cream',
		amount: 0.25,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/4 cup heavy Cream',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Spices and Seasonings',
		name: 'salt',
		amount: 2,
		unit: 'teaspoons',
		unitShort: 't',
		unitLong: 'teaspoons',
		originalString: '2 teaspoons salt',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Baking',
		name: 'sugar',
		amount: 0.25,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/4 cup sugar',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Canned and Jarred',
		name: 'tomatoes',
		amount: 2,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '2 Tomatoes',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Beverages',
		name: 'water',
		amount: 3,
		unit: 'cups',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '3 cups Water',
		metaInformation: [],
		longNameAdditions: []
	}],
	id: 632449,
	title: 'Appetizing Apple and Almond Soup',
	readyInMinutes: 45,
	image: 'Appetizing-Apple-and-Almond-Soup-632449.jpg',
	imageUrls: ['Appetizing-Apple-and-Almond-Soup-632449.jpg']
}, {
	vegetarian: true,
	vegan: false,
	glutenFree: true,
	dairyFree: false,
	veryHealthy: false,
	cheap: false,
	veryPopular: false,
	sustainable: false,
	servings: 2,
	sourceUrl: 'http://www.foodista.com/recipe/SRNHDHGT/caramelized-tofu-gala-apple-salad',
	spoonacularSourceUrl: 'https://spoonacular.com/caramelized-tofu-gala-apple-salad-637067',
	aggregateLikes: 13,
	creditText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
	license: 'CC BY 3.0',
	sourceName: 'Foodista',
	extendedIngredients: [{
		aisle: 'Ethnic Foods',
		name: 'extra firm tofu',
		amount: 14,
		unit: 'ounces',
		unitShort: 'oz',
		unitLong: 'ounces',
		originalString: '14 ounces extra-firm tofu, baked',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'lettuce',
		amount: 3,
		unit: 'cups',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '3 cups green leaf lettuce (I am using baby',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'gala apple',
		amount: 1,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '1 gala apple, peeled and diced',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Baking',
		name: 'pecans',
		amount: 12,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '12 wholes raw pecans',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Beverages',
		name: 'water',
		amount: 0.25,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/4 cup water',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Baking',
		name: 'brown sugar',
		amount: 2,
		unit: 'tablespoons',
		unitShort: 'T',
		unitLong: 'tablespoons',
		originalString: '2 tablespoons brown sugar',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Milk, Eggs, Other Dairy',
		name: 'butter',
		amount: 1,
		unit: 'tablespoon',
		unitShort: 'T',
		unitLong: 'tablespoon',
		originalString: '1 tablespoon butter',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'garlic',
		amount: 2,
		unit: 'cloves',
		unitShort: 'cloves',
		unitLong: 'cloves',
		originalString: '2 cloves garlic, minced',
		metaInformation: [],
		longNameAdditions: []
	}],
	id: 637067,
	title: 'Caramelized Tofu & Gala Apple Salad',
	readyInMinutes: 45,
	image: 'Caramelized-Tofu---Gala-Apple-Salad-637067.jpg',
	imageUrls: ['Caramelized-Tofu---Gala-Apple-Salad-637067.jpg']
}, {
	vegetarian: true,
	vegan: false,
	glutenFree: true,
	dairyFree: false,
	veryHealthy: true,
	cheap: false,
	veryPopular: false,
	sustainable: false,
	servings: 2,
	sourceUrl: 'http://www.foodista.com/recipe/VSV73JDY/quinoa-porridge-with-applesauce-skyr-and-honey-toasted-muesli',
	spoonacularSourceUrl: 'https://spoonacular.com/quinoa-porridge-with-applesauce-skyr-and-honey-toasted-muesli-657674',
	aggregateLikes: 1,
	creditText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
	license: 'CC BY 3.0',
	sourceName: 'Foodista',
	extendedIngredients: [{
		aisle: 'Produce',
		name: 'apples',
		amount: 5,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '5 apples',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Nut butters, Jams, and Honey',
		name: 'honey',
		amount: 1,
		unit: 'tsp',
		unitShort: 't',
		unitLong: 'teaspoon',
		originalString: '1 tsp. honey',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Milk, Eggs, Other Dairy',
		name: 'milk',
		amount: 1,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cup',
		originalString: '1 cup milk',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Cereal',
		name: 'muesli cereal',
		amount: 2,
		unit: 'tbsp',
		unitShort: 'T',
		unitLong: 'tablespoons',
		originalString: '2 tbsp. muesli cereal',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Pasta and Rice',
		name: 'quinoa',
		amount: 1,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cup',
		originalString: '1 cup quinoa',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Baking',
		name: 'vanilla pod',
		amount: 1,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: 'seeds from 1 vanilla pod',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Gourmet',
		name: 'vanilla powder',
		amount: 0.5,
		unit: 'tsp',
		unitShort: 't',
		unitLong: 'teaspoons',
		originalString: '½ tsp. pure vanilla powder',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Beverages',
		name: 'water',
		amount: 3,
		unit: 'cups',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '3 cups Water',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Milk, Eggs, Other Dairy',
		name: 'yogurt',
		amount: 2,
		unit: 'tbsp',
		unitShort: 'T',
		unitLong: 'tablespoons',
		originalString: '2 tbsp. skyr yogurt',
		metaInformation: [],
		longNameAdditions: []
	}],
	id: 657674,
	title: 'Quinoa Porridge with Applesauce, Skyr and Honey Toasted Muesli',
	readyInMinutes: 45,
	image: 'Quinoa-Porridge-with-Applesauce--Skyr-and-Honey-Toasted-Muesli-657674.jpg',
	imageUrls: ['Quinoa-Porridge-with-Applesauce--Skyr-and-Honey-Toasted-Muesli-657674.jpg']
}, {
	vegetarian: true,
	vegan: false,
	glutenFree: true,
	dairyFree: true,
	veryHealthy: false,
	cheap: false,
	veryPopular: false,
	sustainable: false,
	servings: 2,
	sourceUrl: 'http://www.foodista.com/recipe/72TL7P4J/green-salad-with-fresh-orange-juice-dressing',
	spoonacularSourceUrl: 'https://spoonacular.com/green-salad-with-fresh-orange-juice-dressing-645514',
	aggregateLikes: 1,
	creditText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
	license: 'CC BY 3.0',
	sourceName: 'Foodista',
	extendedIngredients: [{
		aisle: 'Produce',
		name: 'apple',
		amount: 1,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '1 green apple,wash and diced',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'carrot',
		amount: 0.5,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/2 cup shredded carrot',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Milk, Eggs, Other Dairy',
		name: 'eggs',
		amount: 2,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '2 hard boiled eggs',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Baking',
		name: 'granulated sugar',
		amount: 1,
		unit: 'tablespoon',
		unitShort: 'T',
		unitLong: 'tablespoon',
		originalString: '1 tablespoon granulated sugar',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Spices and Seasonings',
		name: 'ground pepper',
		amount: 1,
		unit: 'teaspoon',
		unitShort: 't',
		unitLong: 'teaspoon',
		originalString: '1 teaspoon ground white pepper',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'jicama',
		amount: 0.5,
		unit: 'cup',
		unitShort: 'c',
		unitLong: 'cups',
		originalString: '1/2 cup jicama',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'lime',
		amount: 1,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '1 lime',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Oil, Vinegar, Salad Dressing',
		name: 'olive oil',
		amount: 4,
		unit: 'tablespoons',
		unitShort: 'T',
		unitLong: 'tablespoons',
		originalString: '4 tablespoons olive oil',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'oranges',
		amount: 2,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '2 fresh oranges',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Produce',
		name: 'romaine lettuce',
		amount: 1,
		unit: 'head',
		unitShort: 'head',
		unitLong: 'head',
		originalString: '1 head romaine lettuce',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Spices and Seasonings',
		name: 'sea salt',
		amount: 1,
		unit: 'tablespoon',
		unitShort: 'T',
		unitLong: 'tablespoon',
		originalString: '1 tablespoon sea salt',
		metaInformation: [],
		longNameAdditions: []
	}, {
		aisle: 'Canned and Jarred',
		name: 'tomato',
		amount: 1,
		unit: '',
		unitShort: '',
		unitLong: '',
		originalString: '1 tomato',
		metaInformation: [],
		longNameAdditions: []
	}],
	id: 645514,
	title: 'Green Salad With Fresh Orange Juice Dressing',
	readyInMinutes: 15,
	image: 'Green-Salad-With-Fresh-Orange-Juice-Dressing-645514.jpg',
	imageUrls: ['Green-Salad-With-Fresh-Orange-Juice-Dressing-645514.jpg']
}

module.exports = data;